Login
dilo145/chStack pull request #9
Opened 2024-03-06 21:45 UTC by ilyaszk

2024-03-06 22:07 UTC, dilo145 requested changes, later dismissed

2024-03-06 22:07 UTC, dilo145 commented on api/src/Controller/LoginController.php
> +            return new JsonResponse(['error' => 'Missing required fields'], Response::HTTP_OK);
S'il manque des champs, il faut plutôt retourner HTTP_BAD_REQUEST

2024-03-06 22:07 UTC, dilo145 commented on api/src/Controller/LoginController.php
> +            return new JsonResponse(['error' => 'Invalid Email/Password'], Response::HTTP_OK);
Idem HTTP_UNAUTHORIZED

2024-03-06 22:07 UTC, dilo145 commented on api/src/Controller/LoginController.php
> +            return new JsonResponse(['error' => 'Invalid Email/Password'], Response::HTTP_OK);
Idem HTTP_UNAUTHORIZED

2024-03-06 22:07 UTC, dilo145 commented on api/src/Controller/LoginController.php
> +        // if (!$userPasswordHasher->isPasswordValid($user, $data['password'])) {
Supprimer le code inutile si possible

2024-03-06 22:07 UTC, dilo145 commented on api/src/Repository/UserRepository.php
> +    public function findByEmail($value): ?User
Utiliser directement ```$this->entityManager->getRepository(User::class)->findOneBy(['email' => $data["email"]])``` dans le service

2024-03-06 22:07 UTC, dilo145 commented on api/src/Service/StudentService.php
> +    public function deleteStudent(Request $request, int $id): JsonResponse
Le paramètre Request n'est pas nécessaire ici

2024-03-06 22:07 UTC, dilo145 commented on app/src/components/SideNavigationComponent.vue
> +  <!-- Conditional rendering of JSON data -->
À supprimer le commentaire

2024-03-06 22:07 UTC, dilo145 commented on app/src/pages/login.vue
> +  // router.go(-1);
À supprimer le commentaire

2024-03-06 22:07 UTC, dilo145 commented on api/config/packages/security.yaml
> +      # custom_authenticator: App\Security\LoginAuthenticator
À supprimer s'il n'est pas utilisé

2024-03-07 08:25 UTC, mohamedDev69 approved these changes

2024-03-07 08:28 UTC, mohamedDev69 approved these changes

2024-03-07 08:30 UTC, merged